INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS, RESTAURANT_IMAGE)
values(
'Tia Iva',
'Viseu', 
coordinates_type('10','20'),
open_hours_type('10:00','22:00'),
'1',
'1',
'0',
'1',
'1',
'5',
'tia_iva.jpg'
);
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'0 Tosco',
'Vila Cha de Sa', 
coordinates_type('12','20'),
open_hours_type('12:00','23:00'),
'1',
'0',
'0',
'1',
'1',
'3',
'tosco.jpg'
);
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Casa Arouquesa',
'Repeses', 
coordinates_type('13','20'),
open_hours_type('12:00','00:00'),
'1',
'0',
'0',
'1',
'1',
'5',
'casa_arouquesa.jpg'
);
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Maionese',
'Jugueiros', 
coordinates_type('15','30'),
open_hours_type('11:00','23:00'),
'1',
'0',
'0',
'0',
'1',
'4',
'maionese.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Churrasqueira',
'Repeses', 
coordinates_type('20','35'),
open_hours_type('09:00','23:00'),
'0',
'0',
'1',
'0',
'1',
'3',
'churrasqueria.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Vintage',
'Rossio', 
coordinates_type('40','5'),
open_hours_type('09:00','23:00'),
'1',
'1',
'1',
'1',
'1',
'5',
'vintage.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'O Cortiço',
'Viseu', 
coordinates_type('10','51'),
open_hours_type('13:00','23:00'),
'1',
'1',
'0',
'1',
'0',
'5',
'cortiço.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Cantinho do Tito',
'Viseu', 
coordinates_type('1','5'),
open_hours_type('13:00','00:00'),
'1',
'1',
'1',
'1',
'1',
'5',
'cantinho_tito.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Budega',
'Viseu', 
coordinates_type('11','14'),
open_hours_type('19:00','00:00'),
'1',
'1',
'1',
'0',
'0',
'4',
'budega.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'CasaBlanca',
'Viseu', 
coordinates_type('2','10'),
open_hours_type('12:00','22:00'),
'1',
'1',
'1',
'0',
'0',
'3',
'casablanca.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'CB House',
'Viseu', 
coordinates_type('255','010'),
open_hours_type('12:00','02:00'),
'0',
'1',
'1',
'0',
'0',
'3',
'cb.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Forno da Mimi',
'Viseu', 
coordinates_type('150','05'),
open_hours_type('12:00','00:00'),
'1',
'1',
'1',
'1',
'1',
'5',
'forno_mimi.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'O Martelo',
'Viseu', 
coordinates_type('08','05'),
open_hours_type('13:00','23:00'),
'0',
'0',
'0',
'0',
'1',
'2',
'martelo.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
  'Porta da Sé',
'Viseu', 
coordinates_type('081','051'),
open_hours_type('11:00','01:00'),
'0',
'1',
'1',
'1',
'1',
'3',
'portase.png');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'Cervejaria Cacimbo',
'Viseu', 
coordinates_type('00','222'),
open_hours_type('10:00','22:00'),
'0',
'0',
'1',
'0',
'1',
'4',
'cacimbo.jpg');
INSERT INTO Restaurants (RESTAURANT_NAME,RESTAURANT_ADDRESS,RESTAURANT_COORDS,RESTAURANT_OPEN_HOURS,RESTAURANT_RESERVATIONS,RESTAURANT_WIFI, 
RESTAURANT_DELIVERY,RESTAURANT_MULTIBANCO,RESTAURANT_OUTDOOR_SEATING,RESTAURANT_POINTS,RESTAURANT_IMAGE)
values(
'McDonalds',
'Viseu', 
coordinates_type('111','200'),
open_hours_type('9:00','3:00'),
'0',
'0',
'1',
'1',
'1',
'3',
'mac.jpg');


commit;


