SELECT r.RESTAURANT_ID, "RESTAURANT_NAME", "RESTAURANT_ADDRESS",
"RESTAURANT_RESERVATIONS", "RESTAURANT_WIFI", "RESTAURANT_DELIVERY", "RESTAURANT_MULTIBANCO", "RESTAURANT_OUTDOOR_SEATING", "RESTAURANT_POINTS", "RESTAURANT_IMAGE"
FROM RESTAURANTS r 
INNER JOIN COORDS c 
ON r.RESTAURANT_ID = c.RESTAURANT_ID;

WHERE "RESTAURANTS"."RESTAURANT_ID" = '1';
select * from prices;
select * from dishes;
select * from dishes_prices;

drop table DISHES_MENUS;
ALTER TABLE PRICES
ADD CONSTRAINT FK_MENUS
FOREIGN KEY (MENU_ID)
REFERENCES MENUS(MENU_ID);